# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Nair confidence bands
#'
#' Computes the Nair's log-transformed equal-precision simultaneous confidence
#' band¹ for the Kaplan–Meier survival estimator at each unique event time.
#' @param time Numeric vector of unique event times.
#' @param surv Numeric vector of Kaplan–Meier survival probabilities at each
#' `time`.
#' @param SE Numeric vector of standard errors for each `surv`.
#' @param risk Integer vector of numbers at risk at each `time`.
#' @param event Integer vector of numbers of events at each `time`.
#' @param alpha Significance level. Default = `0.05`.
#' @param e_override Optional numeric value overriding the critical value *e*.
#' @return A numeric matrix with 2 columns: lower limit and upper limit.
#' @details
#' The equal-precision critical value *e* is calculated using Borokov–Sycheva
#' approximation² (`WH_e_alpha()`). This method aligns more closely with
#' Monte Carlo simulations using 100 000 Brownian bridge discretization steps
#' and 100 000 replicates (`WH_e_alpha_MC()`) compared to the pre-computed tables
#' published in Klein & Moeschberger (2003)³.
#' @references
#' 1. Nair, V.N., 1984. Conﬁdence bands for survival functions with censored
#' data: a comparative study. *Technometrics*, 26, pp. 265–275.
#' 2. Borokov, A.A. and Sycheva, N.M., 1968. On asymptotically optimal
#' non-parametric criteria. *Theory of Probability & Its Applications*, 13(3),
#' pp. 359–393.
#' 3. Klein, J.P. and Moeschberger, M.L., 2003. Appendix C: Statistical Tables.
#' In *Survival Analysis: Techniques for Censored and Truncated Data*, pp.
#' 455–482. New York: Springer New York.
#' @export
WH_Nair <- function(time, surv, SE, risk, event, alpha = 0.05, e_override = 0.0) {
    .Call(`_WHKMconf_WH_Nair`, time, surv, SE, risk, event, alpha, e_override)
}

#' Rothman confidence intervals
#'
#' Computes Rothman binomial pointwise confidence intervals for the
#' Kaplan–Meier survival estimator at each unique event time.
#' @param surv Numeric vector of Kaplan–Meier survival probabilities.
#' @param risk Integer vector of numbers at risk at each change in `surv`.
#' @param event Integer vector of event counts at each change in `surv`.
#' @param alpha Significance level. Default = `0.05`.
#' @return A numeric matrix with 2 columns: lower limit and upper limit.
#' @export
WH_Rothman <- function(surv, risk, event, alpha = 0.05) {
    .Call(`_WHKMconf_WH_Rothman`, surv, risk, event, alpha)
}

#' Thomas–Grunkemeier confidence intervals
#'
#' Computes Thomas–Grunkemeier likelihood-ratio pointwise confidence intervals
#' for the Kaplan–Meier survival estimator at each unique event time.
#' @param time Numeric vector of unique event times.
#' @param risk Integer vector of numbers at risk at each `time`.
#' @param event Integer vector of numbers of events at each `time`.
#' @param alpha Significance level. Default = `0.05`.
#' @return A numeric matrix with 2 columns: lower limit and upper limit.
#' @export
WH_ThomasGrunkemeier <- function(time, risk, event, alpha = 0.05) {
    .Call(`_WHKMconf_WH_ThomasGrunkemeier`, time, risk, event, alpha)
}

#' Hollander–McKeague confidence bands
#'
#' Computes the Hollander–McKeague likelihood-ratio simultaneous confidence
#' band for the Kaplan–Meier survival estimator at each unique event time.
#' @param time Numeric vector of unique event times.
#' @param risk Integer vector of numbers at risk at each `time`.
#' @param event Integer vector of numbers of events at each `time`.
#' @param alpha Significance level. Default = `0.05`.
#' @param warn Logical; if `TRUE`, prints a message if the *pointwise α* is
#' rounded up.
#' @param tol_G Optional convergence tolerance for the infinite series
#' computing the Hall–Wellner distribution function *G*(*a*, *λ*). Default =
#' `1e-10`.
#' @param maxit_G Optional maximum number of iterations for the infinite series
#' computing the Hall–Wellner distribution function *G*(*a*, *λ*). Default =
#' `10000`.
#' @param tol_K Optional convergence tolerance for the bisection root-finding
#' of the Hall–Wellner quantile function *K*(*x*, *a*). Default = `1e-10`.
#' @param maxit_K Optional maximum number of iterations for the bisection
#' root-finding of the Hall–Wellner quantile function *K*(*x*, *a*). Default =
#' `10000`.
#' @return A numeric matrix with 2 columns: lower limit and upper limit.
#' @details
#' The Hollander–McKeague procedure begins with a specified *simultaneous α* and
#' computes a smaller *pointwise α* such that the resulting *pointwise* confidence
#' intervals achieve the desired *simultaneous* coverage. Extremely small
#' *pointwise α* can cause 1 − *α* to round to 1 in double precision. To prevent
#' this, *pointwise α* is rounded up to at least half the machine epsilon.
#' @export
WH_HollanderMcKeague <- function(time, risk, event, alpha = 0.05, warn = TRUE, tol_G = 1e-10, maxit_G = 10000L, tol_K = 1e-10, maxit_K = 10000L) {
    .Call(`_WHKMconf_WH_HollanderMcKeague`, time, risk, event, alpha, warn, tol_G, maxit_G, tol_K, maxit_K)
}

#' Critical value for Nair's equal-precision confidence bands (Borokov–Sycheva)
#'
#' Computes the critical value *e* for Nair's equal-precision confidence bands¹
#' using Borokov–Sycheva approximation². Note: to reproduce Table 2 of Nair
#' (1984), use `alpha/2`.
#' @param lower Lower limit of supremum evaluation.
#' @param upper Upper limit of supremum evaluation.
#' @param alpha Significance level.
#' @param tol Convergence tolerance. Default = `1e-10`.
#' @param maxit Maximum number of iterations. Default = `10000`.
#' @return The critical value *e*.
#' @references
#' 1. Nair, V.N., 1984. Conﬁdence bands for survival functions with censored
#' data: a comparative study. *Technometrics*, 26, pp. 265–275.
#' 2. Borokov, A.A. and Sycheva, N.M., 1968. On asymptotically optimal
#' non-parametric criteria. *Theory of Probability & Its Applications*, 13(3),
#' pp. 359–393.
#' @export
WH_e_alpha <- function(lower, upper, alpha, tol = 1e-10, maxit = 10000L) {
    .Call(`_WHKMconf_WH_e_alpha`, lower, upper, alpha, tol, maxit)
}

#' Critical value for Nair's equal-precision confidence bands (Monte Carlo)
#'
#' Computes the critical value *e* for Nair's equal-precision confidence bands¹
#' using Monte Carlo simulation. Note: to reproduce Table 2 of Nair (1984), use
#' `alpha/2`.
#' @param lower Lower limit of supremum evaluation.
#' @param upper Upper limit of supremum evaluation.
#' @param alpha Significance level.
#' @param n_step Number of discretization steps for each variance-stabilized
#' Brownian bridge. Default = `1e5`.
#' @param n_rep Number of Monte Carlo replicates. Default = `1e5`.
#' @param seed Random seed. Default = `24601`.
#' @details
#' Parallelized using OpenMP if available.
#' @return The critical value *e*.
#' @references
#' 1. Nair, V.N., 1984. Conﬁdence bands for survival functions with censored
#' data: a comparative study. *Technometrics*, 26, pp. 265–275.
#' @export
WH_e_alpha_MC <- function(lower, upper, alpha, n_step = 1e5L, n_rep = 1e5L, seed = 24601L) {
    .Call(`_WHKMconf_WH_e_alpha_MC`, lower, upper, alpha, n_step, n_rep, seed)
}

